anton()

function anton() {
  alert("GOOD DAY SIR, I AM ANTONIO JR. P. ANDAYA AND THIS IS MY PARTNER JAZHRYLLE A. ESPOSO AND THIS IS OUR OUTPUT IN MAKING 20+ FILES IN WEBSITE DESIGN AND DEVELOPMENT.")
}